# Generated by Django 5.2 on 2025-05-12 17:14

import django.core.validators
import django.db.models.deletion
import product.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=63, unique=True)),
            ],
            options={
                "verbose_name_plural": "Categories",
            },
        ),
        migrations.CreateModel(
            name="Image",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("filename", models.CharField(blank=True, max_length=255)),
                ("image", models.ImageField(upload_to=product.models.movie_image_file_path)),
            ],
        ),
        migrations.CreateModel(
            name="Option",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("color", "Color"),
                            ("clothing_size", "Clothing size"),
                            ("product_size", "Product size"),
                            ("material", "Material"),
                        ],
                        max_length=15,
                    ),
                ),
                ("value", models.CharField(max_length=63)),
            ],
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=7,
                        validators=[django.core.validators.MinValueValidator(0.0)],
                    ),
                ),
                (
                    "discount",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        default=0,
                        null=True,
                        validators=[django.core.validators.MaxValueValidator(100)],
                    ),
                ),
                ("description", models.TextField(blank=True, max_length=2000, null=True)),
                ("amount", models.PositiveIntegerField()),
                ("is_active", models.BooleanField(default=True)),
                (
                    "gender",
                    models.CharField(
                        choices=[("male", "Male"), ("female", "Female"), ("unisex", "Unisex")],
                        default="unisex",
                        max_length=10,
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="products",
                        to="product.category",
                    ),
                ),
                (
                    "images",
                    models.ManyToManyField(
                        blank=True, null=True, related_name="products", to="product.image"
                    ),
                ),
                (
                    "main_image",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="product_main",
                        to="product.image",
                    ),
                ),
                (
                    "options",
                    models.ManyToManyField(
                        blank=True, null=True, related_name="products", to="product.option"
                    ),
                ),
            ],
        ),
    ]
