# Generated by Django 5.2 on 2025-04-26 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="option",
            name="name",
        ),
        migrations.AddField(
            model_name="option",
            name="type",
            field=models.CharField(
                choices=[
                    ("color", "Color"),
                    ("clothing_size", "Clothing_size"),
                    ("product_size", "Product_size"),
                    ("material", "Material"),
                ],
                default="color",
                max_length=15,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="option",
            name="value",
            field=models.CharField(default="color", max_length=63),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="product",
            name="options",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="products",
                to="product.option",
            ),
        ),
    ]
