# Generated by Django 5.2 on 2025-04-26 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "product",
            "0002_remove_option_name_option_type_option_value_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="images",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="products",
                to="product.image",
            ),
        ),
    ]
