# Generated by Django 5.2 on 2025-04-29 15:00

import product.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0003_alter_product_images"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="image",
            name="path",
        ),
        migrations.AlterField(
            model_name="image",
            name="filename",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="image",
            name="image",
            field=models.ImageField(upload_to=product.models.movie_image_file_path),
        ),
        migrations.AlterField(
            model_name="option",
            name="type",
            field=models.CharField(
                choices=[
                    ("color", "Color"),
                    ("clothing_size", "Clothing size"),
                    ("product_size", "Product size"),
                    ("material", "Material"),
                ],
                max_length=15,
            ),
        ),
    ]
