# Generated by Django 5.2 on 2025-05-12 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="is_admin",
        ),
        migrations.RemoveField(
            model_name="user",
            name="is_buyer",
        ),
        migrations.RemoveField(
            model_name="user",
            name="is_moderator",
        ),
        migrations.RemoveField(
            model_name="user",
            name="is_seller",
        ),
    ]
