# Generated by Django 5.2 on 2025-04-25 20:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("cart", "0001_initial"),
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PaymentMethod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=63, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Checkout",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_payed", models.BooleanField(default=False)),
                ("is_address_differs", models.BooleanField(default=False)),
                (
                    "payment_finalized_timestamp",
                    models.DateTimeField(null=True),
                ),
                ("first_name_delivery", models.CharField(max_length=63)),
                ("last_name_delivery", models.CharField(max_length=63)),
                ("country_delivery", models.CharField(max_length=255)),
                ("city_delivery", models.CharField(max_length=255)),
                ("street_name_delivery", models.CharField(max_length=255)),
                (
                    "house_number_delivery",
                    models.CharField(blank=True, max_length=63, null=True),
                ),
                (
                    "first_name_payment",
                    models.CharField(blank=True, max_length=63, null=True),
                ),
                (
                    "last_name_payment",
                    models.CharField(blank=True, max_length=63, null=True),
                ),
                (
                    "country_payment",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "city_payment",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "street_name_payment",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "house_number_payment",
                    models.CharField(blank=True, max_length=63, null=True),
                ),
                (
                    "cart",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cart.cart",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="user.user",
                    ),
                ),
                (
                    "payment_method",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="checkout.paymentmethod",
                    ),
                ),
            ],
        ),
    ]
