# Generated by Django 5.2 on 2025-05-19 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0003_alter_order_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="cart",
        ),
        migrations.AddField(
            model_name="order",
            name="payu_order_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="redirect_url",
            field=models.URLField(blank=True, max_length=511, null=True),
        ),
    ]
