# Generated by Django 5.2 on 2025-05-19 16:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0004_remove_order_cart_order_payu_order_id_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cart",
            name="cart_entries",
        ),
        migrations.AddField(
            model_name="cartentry",
            name="cart",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cart_entries",
                to="order.cart",
            ),
            preserve_default=False,
        ),
    ]
