name: Run Django Unit Tests

on:
  pull_request:
    types: [opened, synchronize, reopened, edited, ready_for_review]

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install

      - name: Detect changed apps
        id: detect_apps
        run: |
          echo "Finding changed apps..."
          CHANGED_APPS=$(git diff --name-only origin/${{ github.base_ref }}...${{ github.head_ref }} | grep '/' | cut -d'/' -f1 | sort -u | grep -E '^(app1|app2|app3)$' || true)
          echo "Changed apps: $CHANGED_APPS"
          echo "apps=$CHANGED_APPS" >> $GITHUB_OUTPUT

      - name: Run tests for changed apps
        if: steps.detect_apps.outputs.apps != ''
        run: |
          for app in ${{ steps.detect_apps.outputs.apps }}; do
            echo "Running tests for $app..."
            python manage.py test $app
          done

      - name: No apps changed
        if: steps.detect_apps.outputs.apps == ''
        run: |
          echo "No apps changed. Skipping tests."
